notifications:
    webhooks:
        urls:
            - https://webhooks.gitter.im/e/90c139c7c84b7aab80d9
        on_success: change  # options: [always|never|change] default: always
        on_failure: always  # options: [always|never|change] default: always
        on_start: false     # default: false
language: node_js
node_js:
    - "node"
cache:
    directories:
        - node_modules
after_script:
    - "npm run-script coverage"
    - "cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js"
